# Reference: https://hub.docker.com/r/bitnami/moodle
# TODO: make the volume persisted on the machine and shared with the container

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=<your_moodle_user>
      - MARIADB_DATABASE=<your_moodle_db_name>
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.5
    container_name: moodle
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=<your_moodle_user>
      - MOODLE_DATABASE_NAME=<your_moodle_db_name>
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=<your_admin_user>
      - MOODLE_PASSWORD=<your_admin_password>
      - MOODLE_HOST=<your_domain>
      - MOODLE_REVERSEPROXY=true
      - MOODLE_SSLPROXY=true
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local