
---
- name: Setup Let's Encrypt with Nginx on Docker
  hosts: your_servers
  become: yes
  tasks:
    - name: Create the project directory
      file:
        path: "/home/{{ ansible_user }}/letsencrypt"
        state: directory
        mode: '0755'

    - name: Create docker-compose.yml file
      copy:
        dest: "/home/{{ ansible_user }}/letsencrypt/docker-compose.yml"
        content: |
          version: '3'
          services:
            webserver:
              image: nginx:latest
              ports:
                - "80:80"
                - "443:443"
              restart: always
              volumes:
                - ./nginx/conf/:/etc/nginx/conf.d/:ro
                - ./certbot/www/:/var/www/certbot/:ro
            certbot:
              image: certbot/certbot:latest
              volumes:
                - ./certbot/www/:/var/www/certbot/:rw
                - ./certbot/conf/:/etc/letsencrypt/:rw

    - name: Create Nginx configuration file
      copy:
        dest: "/etc/nginx/conf.d/app.conf"
        content: |
          server {
              listen 80;
              listen [::]:80;
              server_name {{ domain_name }} www.{{ domain_name }};
              server_tokens off;
              location /.well-known/acme-challenge/ {
                  root /var/www/certbot;
              }
              location / {
                  return 301 https://{{ domain_name }}$request_uri;
              }
          }

    - name: Run Certbot dry run
      command: >
        docker-compose run --rm certbot renew --dry-run
      chdir: "/home/{{ ansible_user }}/letsencrypt"
      register: dry_run_result
      ignore_errors: yes

    - name: Fail if dry run failed
      fail:
        msg: "Certbot dry run failed. Please check the configuration."
      when: dry_run_result.rc != 0

    - name: Run Certbot to generate certificates
      command: >
        docker-compose run --rm certbot certonly --webroot
        --webroot-path=/var/www/certbot
        --email {{ certbot_email }}
        --agree-tos
        --no-eff-email
        -d {{ domain_name }}
      when: dry_run_result.rc == 0
      chdir: "/home/{{ ansible_user }}/letsencrypt"

    - name: Start Nginx container
      command: docker-compose up -d webserver
      chdir: "/home/{{ ansible_user }}/letsencrypt"
